
---
- hosts: all
  connection: network_cli
  gather_facts: 'no'
  vars_files:
    - router2-ospf.yml

  tasks: 
    - name: A Loop example 
      template: 
        src: ./template_if.j2 
        dest: ./jinja3/output_router2.txt

    - name: OUTPUT 
      shell:
        cmd: cat ./jinja3/output_router2.txt
