---

- hosts: all

  connection: network_cli
  gather_facts: 'no'
  
  tasks:
    - name: ejecutar comandos y comprobar salidas
      vyos_command:
        commands:
        - show version
        - show hardware cpu
       
        wait_for:
        - result[0] contains Version{{':'}}          VyOS 1.3.0-rc4
        - result[0] contains Copyright{{':'}}        VyOS maintainers and contributors
        - result[0] contains Hardware vendor{{':'}}  QEMU
        
        - result[1] contains CPU(s){{':'}}              1

      register: variable
      


          
    - name: sacar valores de retorno
      debug:
        msg: "{{ variable.stdout_lines }}"
