---

- hosts: all

  connection: network_cli
  gather_facts: 'no'
  
  tasks:
    - name: ejecutar comandos y comprobar salidas
      vyos_command:
        commands:
        - show version
        - show hardware cpu
       
        wait_for:
        - result[0] contains 'VyOS 1.3.0-rc4'
        - result[1] contains '40 bits physical'
        
        register: variable
        

          
    - name: sacar valores de retorno
      debug:
        msg: "{{ variable.commands }}"
      
