---

- hosts: all

  connection: network_cli
  gather_facts: 'no'
  
  tasks:
    - name: ejecutar comandos y comprobar salidas
      vyos_command:
        commands:
        - show version
        - show hardware cpu
       
        wait_for:
        - result[0] contains "Version{{':'}}          VyOS 1.3.0-rc4"
        - result[0] contains "Build UUID{{':'}}       8d9996d2-511e-4dea-be4f-cd4515c404f3"
        - result[0] contains "System type{{':'}}      KVM guest"
                
        - result[1] contains "Architecture{{':'}}        x86_64"
        - result[1] contains "CPU(s){{':'}}              1"
        - result[1] contains "Thread(s) per core{{':'}}  1"


      register: variable
  
          
    - name: sacar valores de retorno del moludo command
      debug:
        msg: "{{ result[0] }}"
        
    - name: sacar salida de los comandos que se han metido
      debug:
        msg: "{{ variable.stdout_lines }}"         
