---

- hosts: all

  connection: network_cli
  gather_facts: 'no'
  
  tasks:
  
    - name: crear interfaz eth1 y dos VLANs
      vyos_l3_interfaces:
        config:
        - name: eth1
          ipv4:
          - address: 170.1.1.1/24
          vifs:
          - vlan_id: 200
            ipv4:
            - address: 200.1.1.1/28
          - vlan_id: 100
            ipv4:
            - address: 100.1.1.1/28

          
      register: variable
        
        
    - name: sacar valores de retorno del moludo command
      debug:
        msg: "{{ variable }}"         
   


