---

- hosts: all

  connection: network_cli
  gather_facts: 'no'
  
  tasks:
  
    - name: Merge provided configuration with device configuration
      vyos_interfaces:
      config:
      - name: eth1
        description: Configured by Ansible
        enabled: true
        vifs:
        - vlan_id: 100
          description: VIF 100 - ETH1    
          
   


