---

- hosts: all

  connection: network_cli
  gather_facts: 'no'
  
  tasks:
  
    - name: crear interfaz
      vyos_l3_interfaces:
        config:
        - name: eth1
          ipv4:
            - address: 172.1.1.1/24
          
          
    - name: Create vlan
      vyos_vlan:
        interfaces: eth1
        vlan_id: 100
        name: vlan-100

   
              

