---

- hosts: all

  connection: network_cli
  gather_facts: 'no'
  
  tasks:
  
    - name: Crear interfaces
      vyos_interfaces:
        config:
        - name: eth3
          description: descripcion interfaz eth3
          duplex: full
          enabled: true
          
        - name: eth4
          description: descripcion interfaz eth4
          duplex: full
          enabled: true
           
        

