---

- hosts: all

  connection: network_cli
  gather_facts: 'no'
  
  tasks:
  
    - name: Merge provided configuration with device configuration
      vyos_l3_interfaces:
        config:
        - name: eth2

         
        

