---

- hosts: all

  connection: network_cli
  gather_facts: 'no'
  
  tasks:
  
    - name: Crear interfaces
      vyos_l3_interfaces:
        config:
        - name: eth1
          ipv4:
          - address: 172.1.1.1/24

        - name: eth2
          ipv4:
          - address: 172.1.1.2/24
          

           
        

