---

- hosts: all

  connection: network_cli
  gather_facts: 'no'
  
  tasks:
  
    - name: Crear interfaces
      vyos_interfaces:
        config:
        - name: eth1
          description: descripcion interfaz eth1
          duplex: full
          enabled: true
          
        - name: eth2
          description: descripcion interfaz eth2
          duplex: full
          enabled: true
             
        register: variable
        
        
    - name: sacar valores de retorno del moludo command
      debug:
        msg: "{{ variable }}"
