---

- hosts: all

  connection: network_cli
  gather_facts: 'no'
  
  tasks:
  
    - name: Merge provided configuration with device configuration
      vyos_l3_interfaces:
        config:
        - name: eth2
          ipv4:
            - address: 172.1.1.2/24
              

