---

- hosts: all

  connection: network_cli
  gather_facts: 'no'
  
  tasks:
  
    - name: Crear interfaces
      vyos_l3_interfaces:
        config:
        - name: eth1
          ipv4:
          - address: 172.1.1.1/24

        - name: eth2
          ipv4:
          - address: 172.1.1.2/24
          
    - name: Configurar interfaces
      vyos_interfaces:
        config:
        - name: eth1
          description: descripcion interfaz eth3
          duplex: full
          enabled: true

        - name: eth2
          description: descripcion interfaz eth4
          duplex: full
          enabled: true
           
        

