---
- hosts: all
  connection: network_cli
  gather_facts: 'no'
  
  tasks:
    - name: Get Config for Vyos Device
      vyos_facts:
        gather_subset: config

    - name: Display config
      debug:
        msg: "The config is {{ ansible_net_config }}"    

        
     
