---

- hosts: all

  connection: network_cli
  gather_facts: 'no'
  
  tasks:
    - name: Get Config for Vyos Device
      vyos_facts:
        gather_subset: config
        register: data_struct
        
    - name: Enseña la configuracion
      debug:
        msg: "The config is {{ data_struct }}"        
        
        

        
     
