---

- hosts: all

  connection: network_cli
  gather_facts: 'no'
  
  tasks:
    - name: Configure hostname
      vyos_config:
        lines:
          - set system host-name {{ hostname_equipo }}
          
    - name: Hello to
      debug:
        msg: "Good morning {{ nombre_persona}} !!"
