---

- hosts: all

  connection: network_cli
  gather_facts: 'no'
  
  tasks:
    - name: Configure mtu
      vyos_interfaces:
        config:
        - name: eth0
          description: "esto es la descripcion de la interfaz"
          mtu: 8000
     
