---

- hosts: all

  connection: network_cli
  gather_facts: 'no'
  
  tasks:
    - name: print hola
      debug:
        msg: "hola"
        
    - name: Configure mtu
      vyos_interfaces:
        config:
        - name: eth0
          description: "esto es la descripcion de la interfaz"
          mtu: 6000
      register: variable
          
    - name: print all returned values
      debug:
        msg: "{{ variable.commands }}"

         
          
     
