---

- hosts: all

  connection: network_cli
  gather_facts: 'no'
  
  tasks:
    - name: ejecutar comandos y comprobar salidas
      vyos_command:
        commands:
        - "{{ comando1 }}"
        - "{{ comando2 }}"
        - "{{ comandos }}"  
        
      register: variable
        
    - name: sacar salida de los comandos que se han metido
      debug:
        msg: "{{ variable.stdout_lines }}"
