---

- hosts: all

  connection: network_cli
  gather_facts: 'no'
  
  tasks:
    - name: ejecutar comandos show
      vyos_command:
        commands:
        - "{{ comando1 }}"
        - "{{ comando2 }}"
        - "{{ comando3 }}"  
        
      register: variable
        
    - name: sacar salida de los comandos que se han metido
      debug:
        msg: "{{ variable.stdout_lines }}"
