---
- hosts: all
  connection: network_cli
  gather_facts: 'no'
  vars_files:
    - vars.yml

  tasks:
    - name: Render config for host
      template:
        src = ./template.j2
        dest = ./output.txt

    - name: OUTPUT 
      shell:
        cmd: cat ./output.txt
