---
- hosts: all
  connection: network_cli
  gather_facts: 'no'
  vars_files:
    - vars.yml

  tasks: 
    - name: PROBANDO
      template: 
        src: ./template.j2 
        dest: ./jinjaZZZ/output.txt

    - name: OUTPUT 
      shell:
        cmd: cat ./jinjaZZZ/output.txt
