
---
- hosts: all
  connection: network_cli
  gather_facts: 'no'
  vars : 
    cars: ['Mercedes','Ford','Nissan', 'Audi', 'Ferrari']

  tasks: 
    - name: A Loop example 
      template: 
        src: ./template.j2 
        dest: ./jinja1/output.txt

    - name: OUTPUT 
      shell:
        cmd: cat ./jinja1/output.txt

