from docx import Document
from docx.shared import Inches
from docx.shared import Pt

document = Document()
style = document.styles['Normal']
font = style.font
font.name = 'Arial'
font.size = Pt(9)


document.add_heading('Plantillas de Configuración Básica de Gestión para Equipamiento Cisco', 0)
document.add_page_break()

document.add_heading('1. INTRODUCCION', 1)

document.add_heading('1.1. Objetivo', 2)
document.add_paragraph('Este documento presenta las plantillas de configuración básica de gestión comunes a todos los routers y switches de Cisco Networks homologados para su utilización como EDCs en los servicios de GGEE, en sus diferentes modalidades.')
document.add_paragraph('En este documento se han incluido plantillas de configuración para los equipos que se indican a continuación:')
document.add_paragraph('Cisco 892FSP, versión 15.4(3)M3 ')
document.add_paragraph('Familia ISR1100, versión 16.9.4')
document.add_paragraph('Familia ISR4000, versión 16.9.4')
document.add_paragraph('Cisco ASR1001-X, versión 16.9.4		')
document.add_paragraph('Cisco ASR1009-X, versión 16.9.6')
document.add_paragraph('Cisco ASR920. Versión 16.9.4 ')
document.add_paragraph('Cisco ASR903, versión 16.12.3')
document.add_paragraph('Cisco C9200L, versión 16.12.4')
document.add_paragraph('Cisco C9300L, versión 16.12.4')
document.add_paragraph('Cisco C1000, versión 15.2(7)E3k	 ')
document.add_paragraph('Aquellas configuraciones de gestión que no sean genéricas se podrán consultar en las plantillas del servicio correspondiente.')
document.add_paragraph('Toda la parte de QoS referente a la clase de Gestión se mantiene en las plantillas estándar para conservar la homogeneidad y el orden en la configuración de las clases. Lo mismo ocurre con la configuración de routing.')

document.add_heading('1.2. Documentación de referencia', 2)
document.add_paragraph('Como documentación de referencia se ofrecen los siguientes manuales de plantillas:')
document.add_paragraph('•	DTSRPV-2003 MacroLAN_plantillas_Cisco_Switch_vX.X')
document.add_paragraph('•	DTSRPV-2005 MacroLAN_Plantillas_Cisco_Router_vX.X')
document.add_paragraph('•	Plantillas de Configuracion del Servicio VPN IP para Equipos de Cliente Cisco (vX.XX.XX)')
document.add_paragraph('•	Plantillas Ibercom IP Puntos Centrales Generico Switches Cisco vX.XX.XX')
document.add_paragraph('•	Plantillas_Datainternet_BA_vX.X')
document.add_paragraph('•	Plantillas_SILAN_ConWiFi_Switches_Cisco_vX.XX')

document.add_heading('1.3. Unidad responsable', 2)
document.add_paragraph('D. Desarrollo de Servicios y Sistemas')
document.add_paragraph('D. Desarrollo de Servicios Empresas ')
document.add_paragraph('•	G. Certificación Equipamiento de Cliente')
document.add_paragraph('o	J. Equipamiento de Soluciones de Datos')

document.add_heading('2. PLANTILLAS DE CONFIGURACION', 1)

document.add_heading('2.1. Configuración común a todos los servicios', 2)

document.add_heading('2.1.1. Definición del banner', 3)
document.add_paragraph('Desde el modo de configuración del equipo, se especifica el banner que se mostrará antes de que el usuario introduzca sus credenciales de acceso:')
document.add_paragraph('banner login @ {{Texto_Banner_Pre_Autenticacion}} @ ')
document.add_paragraph('{{Texto_Banner_Pre_Autenticacion}}: esto es la explicacion')
document.add_paragraph('A continuación, se introduce el banner que se mostrará una vez que el usuario haya sido autenticado correctamente:')
document.add_paragraph('banner exec @ {{Texto_Banner_Post_Autenticacion}} @ ')
document.add_paragraph('{{Texto_Banner_Post_Autenticacion}}')
document.add_paragraph('NOTA: La escritura de los <Texto_Banner> debe comenzar y terminar con un <Caracter_Delimitador> (%, &, $, @, …) para funcionar correctamente. Además, este carácter no se puede utilizar dentro de <Texto_Banner>. Durante la introducción del texto es posible utilizar la tecla Enter para producir saltos de línea. Cada línea admite un máximo de 255 caracteres.')

document.add_heading('2.1.2. Configuración de fecha y zona horaria', 3)
document.add_paragraph('Desde el modo enable, se ajusta la fecha y hora locales del equipo.')
document.add_paragraph('clock set {{hora_minuto_segundo}} {{dia}} {{mes}} {{ano}}')
document.add_paragraph('{{hora_minuto_segundo}} formato <hh(0-23):mm(0-59):ss(0-59)>')
document.add_paragraph('{{dia}} formato <día(1-31)>')
document.add_paragraph('{{mes}} formato <mes(January..December)>')
document.add_paragraph('Desde el modo de configuración, se configura la zona horaria y los parámetros del cambio de horario de verano.')
document.add_paragraph('{% if localizacion_canarias == false %}')
document.add_paragraph('clock timezone MET 1')
document.add_paragraph('{% endif %}')
document.add_paragraph('clock summer-time METDST recurring last Sun Mar 2:00 last Sun oct 3:00 ')

document.add_heading('2.1.3. Nombre del equipo', 3)
document.add_paragraph('Asignación del mnemónico del EDC. Desde el modo de configuración:')
document.add_paragraph('hostname {{Mnemonico_EDC}} ')
document.add_paragraph('{{Mnemonico_EDC}} ')

document.add_heading('2.1.4.  Desactivacion de servicios no necesarios', 3)
document.add_paragraph('Por motivos de seguridad, se desactivarán una serie de protocolos y servicios que no van a ser utilizados en el EDC. Desde el modo de configuración:')
document.add_paragraph('no cdp run')
document.add_paragraph('no service tcp-small-servers ')
document.add_paragraph('no service udp-small-servers ')
document.add_paragraph('no service finger')
document.add_paragraph('no service dhcp')
document.add_paragraph('{% if modelo_equipo != "Cisco C1000"  %}')
document.add_paragraph('no ip source-route           ')
document.add_paragraph('{% endif %}')
document.add_paragraph('no ip domain-lookup')
document.add_paragraph('no service config')
document.add_paragraph('no ip bootp server   !!! * ')
document.add_paragraph('no ip name-server')
document.add_paragraph('* Determinados modelos no admiten este comando al no disponer de la funcionalidad, por lo que no es problemático si al introducirlo da error.')
document.add_paragraph('Configuración de otros parámetros generales. Desde el modo de configuración:')
document.add_paragraph('service nagle')
document.add_paragraph('service tcp-keepalives-in')
document.add_paragraph('ip subnet-zero')
document.add_paragraph('service timestamps debug datetime localtime msec show-timezone')
document.add_paragraph('service timestamps log datetime localtime msec show-timezone')

document.add_heading('2.1.5.  Gestión por loopback', 3)
document.add_paragraph('Se crea la interfaz loopback de gestión.')
document.add_paragraph('interface loopback 600')
document.add_paragraph('    description Direccion IP de gestion EDC')
document.add_paragraph('    ip address {{IPGestion}} 255.255.255.255')
document.add_paragraph('    no ip directed-broadcast')
document.add_paragraph('    no ip proxy-arp')
document.add_paragraph('    no shutdown')
document.add_paragraph('exit')
document.add_paragraph('ip tftp source-interface Loopback 600')
document.add_paragraph('ip ftp source-interface Loopback 600')
document.add_paragraph('ip tacacs source-interface Loopback 600')
document.add_paragraph('logging source-interface Loopback 600')
document.add_paragraph('snmp-server trap-source Loopback 600')
document.add_paragraph('ntp source Loopback 600')
document.add_paragraph('{{IPGestion}}: Es la dirección IP utilizada para la gestión del EDC. Por tanto, debe ser única en todo el ámbito del servicio.')

document.add_heading('2.1.6. Control de acceso al EDC', 3)

document.add_heading('2.1.6.1. Escenarios con EDC Simple', 4)
document.add_paragraph('Activacion del servicio de encriptado de passwords ')
document.add_paragraph('service password-encryption')
document.add_paragraph('Configuración de la contraseña de acceso al modo enable (también se usará para autenticar los accesos a este modo cuando el servidor TACACS+ esté inaccesible):  ')
document.add_paragraph('enable secret {{Password_Enable}}')
document.add_paragraph('{{Password_Enable}}')
document.add_paragraph('Se crea un usuario local que permitirá el acceso al equipo vía consola y remoto mientras no se configuren las funcionalidades de AAA o cuando el servidor TACACS+ esté innacesible.  ')
document.add_paragraph('username {{Usuario}} secret {{Password_Usuario}}')
document.add_paragraph('{{Usuario}} ')
document.add_paragraph('{{Password_Usuario}}')
document.add_paragraph('Habilita el acceso SSH al equipo  ')
document.add_paragraph('{% if modelo_equipo =="Cisco ASR903" or modelo_equipo =="Cisco ASR920" or modelo_equipo =="Cisco ASR1000" or modelo_equipo =="Familia ISR4000" or modelo_equipo =="Familia ISR1100" or modelo_equipo =="Cisco ASR1009-X" %}')
document.add_paragraph('ip domain name {{Mnemonico_EDC}}')
document.add_paragraph('{% else %}')
document.add_paragraph('ip domain-name {{Mnemonico_EDC}}')
document.add_paragraph('{% endif %}')
document.add_paragraph('crypto key generate rsa')
document.add_paragraph('1024')
document.add_paragraph('ip ssh version 2')
document.add_paragraph('{{Mnemonico_EDC}}')
document.add_paragraph('Se crea un filtro para controlar los accesos remotos al equipo, que sufrirá algunas modificaciones en función del servicio que se esté configurando.  ')
document.add_paragraph('Servicios MacroLAN, VPNIP y DataInternet')
document.add_paragraph('{% if servicio == "MacroLAN" or  servicio == "VPNIP" or servicio == "DataInternet" %}')
document.add_paragraph('    access-list 52 remark Accesos Remotos')
document.add_paragraph('    {% for CentroGestion in CentrosGestion_MACROLAN_VPNIP_DATAINTERNET %}')
document.add_paragraph('    access-list 52 permit {{CentroGestion.IP_CentroGestion}} {{CentroGestion.MascaraInversa}} ')
document.add_paragraph('    {% endfor %}')
document.add_paragraph('    access-list 52 permit host {{IP_PE_1}}')
document.add_paragraph('    access-list 52 permit host {{IP_PE_2}}')
document.add_paragraph('    {% if VLAN_Servicio_respaldo %}')
document.add_paragraph('    access-list 52 permit host {{IP_PE_3}}')
document.add_paragraph('    access-list 52 permit host {{IP_PE_4}}')
document.add_paragraph('    {% endif %}')
document.add_paragraph('    access-list 52 deny any')
document.add_paragraph('{% endif %}')
document.add_paragraph('{{CentroGestion.IP_CentroGestion}} Es una red IP del Centro de Gestión desde la que se quiere acceder vía remota al equipo.')
document.add_paragraph('{{CentroGestion.MascaraInversa}} ')
document.add_paragraph('{{IP_PE_1}} Son cada una de las direcciones IP de los PEs sobre la VLAN de Servicio.')
document.add_paragraph('{{IP_PE_2}} Son cada una de las direcciones IP de los PEs sobre la VLAN de Servicio.-#}')
document.add_paragraph('{{IP_PE_3}} En el servicio MacroLAN, son las direcciones IP de los PEs sobre la VLAN de Servicio de respaldo en escenarios de EDC único con redundancia de acceso y Caudales Exclusivos.-#}')
document.add_paragraph('{{IP_PE_4}} En el servicio MacroLAN, son las direcciones IP de los PEs sobre la VLAN de Servicio de respaldo en escenarios de EDC único con redundancia de acceso y Caudales Exclusivos.-#}')
document.add_paragraph('Servicios SiLAN e Ibercom Punto Central')
document.add_paragraph('{% if servicio == "SILAN" or  servicio == "Ibercom Punto Central" or servicio == "DataInternet" %}')
document.add_paragraph('    access-list 52 remark Accesos Remotos')
document.add_paragraph('    {% for CentroGestion in CentrosGestion_SILAN_IBERCOM %}')
document.add_paragraph('    access-list 52 permit {{CentroGestion.IP_CentroGestion}} {{CentroGestion.MascaraInversa}} ')
document.add_paragraph('    {% endfor %}')
document.add_paragraph('    access-list 52 permit  {{Red_VLAN_Gestion}}  {{MascaraInversa_VLAN_Gestion}}')
document.add_paragraph('    access-list 52 deny any')
document.add_paragraph('{% endif %}')
document.add_paragraph('{{CentroGestion.IP_CentroGestion}}')
document.add_paragraph('{{CentroGestion.MascaraInversa}}')
document.add_paragraph('{{Red_VLAN_Gestion}} Se incluye la red configurada en la VLAN 30 que permitirá el acceso remoto desde los EDCs Principal y Backup y el salto entre switches.-#}')
document.add_paragraph('{{MascaraInversa_VLAN_Gestion}}-#}')
document.add_paragraph('Se limita el número máximo de sesiones simultáneas a 5. También se configuran los tiempos de desconexión por inactividad. La línea "login local" hay que configurarla antes de introducir el comando "aaa new-model" del apartado 2.1.7, ya que en caso contrario el equipo no lo aceptará. ')
document.add_paragraph('Se aplica la lista de acceso a los interfaces VTY y al puerto auxiliar (en caso de que exista):')
document.add_paragraph('line con 0')
document.add_paragraph('login local')
document.add_paragraph('exec-timeout   {{Timeout}}  ')
document.add_paragraph('exit')
document.add_paragraph('{% if tiene_puerto_auxiliar %}')
document.add_paragraph('{% if modelo_equipo != "Cisco ASR920" and modelo_equipo != "Cisco ASR903" and modelo_equipo != "Familia ISR4000" and modelo_equipo != "Familia ISR1100" %} ')
document.add_paragraph('line aux 0')
document.add_paragraph('login local')
document.add_paragraph('exec-timeout   {{Timeout}}   ')
document.add_paragraph('transport input telnet ssh')
document.add_paragraph('transport output telnet ssh')
document.add_paragraph('access-class 52 in')
document.add_paragraph('exit')
document.add_paragraph('{% endif %}')
document.add_paragraph('{% endif %}')
document.add_paragraph('line vty 0 4')
document.add_paragraph('login local')
document.add_paragraph('exec-timeout  {{Timeout}} ')
document.add_paragraph('transport input telnet ssh')
document.add_paragraph('transport output telnet ssh')
document.add_paragraph('access-class 52 in')
document.add_paragraph('exit')
document.add_paragraph('line vty 5 15')
document.add_paragraph('transport input none')
document.add_paragraph('transport output none')
document.add_paragraph('exit')
document.add_paragraph('{% if modelo_equipo == "Familia ISR1100" or modelo_equipo == "Familia ISR4000" %}')
document.add_paragraph('line 2')
document.add_paragraph('transport input none')
document.add_paragraph('exit')
document.add_paragraph('{% endif  %}')
document.add_paragraph('{{Timeout}} Es el tiempo de inactividad en minutos que provocará la desconexión de la sesión.-#}')
document.add_paragraph('Desactivacion de los servidores HTTP/HTTPS  ')
document.add_paragraph('no ip http server')
document.add_paragraph('no ip http secure-server')

document.add_heading('2.1.6.2. Escenarios con dos o más EDCs', 4)
document.add_paragraph('Además de configurar todo lo indicado en el apartado 2.1.6.1, se incluyen los siguientes comandos.')
document.add_paragraph('Se permitirá en todos los EDCs el acceso remoto desde el resto de EDCs de la sede. Es imprescindible que dentro de la ACL 52 la nueva regla se situe por encima del "deny any", que siempre debe ser la última expresión de la lista.')
document.add_paragraph('{% if servicio == "VARIOS EDC" %}')
document.add_paragraph('    no access-list 52')
document.add_paragraph('    access-list 52 remark Accesos Remotos')
document.add_paragraph('    {% for CentroGestion in CentrosGestion_MACROLAN_VPNIP_DATAINTERNET %}')
document.add_paragraph('    access-list 52 permit {{CentroGestion.IP_CentroGestion}} {{CentroGestion.MascaraInversa}} ')
document.add_paragraph('    {% endfor %}')
document.add_paragraph('    access-list 52 permit host {{IP_PE_1}}')
document.add_paragraph('    access-list 52 permit host {{IP_PE_2}}')
document.add_paragraph('    {% if VLAN_Servicio_respaldo %}')
document.add_paragraph('    access-list 52 permit host {{IP_PE_3}}')
document.add_paragraph('    access-list 52 permit host {{IP_PE_4}}')
document.add_paragraph('    {% endif %}')
document.add_paragraph('    {% for IP_LAN_EDC in IPs_LAN_EDC  %}')
document.add_paragraph('    access-list 52 permit host  {{IP_LAN_EDC.IP}} ')
document.add_paragraph('    {% endfor %}')
document.add_paragraph('    access-list 52 deny any')
document.add_paragraph('{% endif  %}')
document.add_paragraph('{{CentroGestion.IP_CentroGestion}}')
document.add_paragraph('{{CentroGestion.MascaraInversa}} ')
document.add_paragraph('{{IP_PE_1}}')
document.add_paragraph('{{IP_PE_2}}')
document.add_paragraph('{{IP_PE_3}}')
document.add_paragraph('{{IP_PE_4}}')
document.add_paragraph('{{IP_LAN_EDC.IP}} Es la IP dentro de la LAN, puede cambiar en función de los servicios contratados por el cliente: ')
document.add_paragraph('                  •	Si existe el servicio SiLAN, será la IP asignada al resto de EDCs en la VLAN de Gestión.')
document.add_paragraph('                  •	En cualquier otro caso, será la IP asignada al resto de EDCs en la LAN de cliente.-#}')
document.add_paragraph('Para ello, se debe eliminar la ACL de manera completa.')
document.add_paragraph('no access-list 52')
document.add_paragraph('Y a continuación volver a crearla con todos los términos, tal y como se indica arriba.')
document.add_paragraph('Una vez realizadas las modificaciones, es recomendable comprobar que sobre las lines vty 0 4 sigue aplicado el comando "access-class 52 in".')

document.add_heading('2.1.7. Configuración TACACS+', 3)
document.add_paragraph('Antes de continuar, es necesario haber creado el usuario local y seguido todos los pasos indicados en el apartado 2.1.6 para evitar posibles pérdidas de conectividad con el EDC.')
document.add_paragraph('Creación de un nuevo modelo de AAA.')
document.add_paragraph('aaa new-model')
document.add_paragraph('no tacacs-server directed-request')
document.add_paragraph('Configuracion de los servidores TACACS+ ')
document.add_paragraph('{% for servidor_TACACS in servidores_TACACS %}')
document.add_paragraph('tacacs server TACACS+_{{loop.index}} ')
document.add_paragraph('address ipv4  {{servidor_TACACS.IP_Servidor}} ')
document.add_paragraph('key  {{servidor_TACACS.CLAVE_Servidor}} ')
document.add_paragraph('exit')
document.add_paragraph('{% endfor %}')
document.add_paragraph('aaa group server tacacs+ TACACS+CG')
document.add_paragraph('{% for servidor_TACACS in servidores_TACACS %}')
document.add_paragraph('server name TACACS+_{{loop.index}} ')
document.add_paragraph('{% endfor %}')
document.add_paragraph('exit')
document.add_paragraph('{{loop.index}}')
document.add_paragraph('{{servidor_TACACS.IP_Servidor}}')
document.add_paragraph('{{servidor_TACACS.CLAVE_Servidor}}')
document.add_paragraph('Para equipos con versiones anteriores a las indicadas, que no admitan los nuevos comandos, se utilizará el antiguo modelo de configuración.')
document.add_paragraph('{% for servidor_TACACS in servidores_TACACS %}')
document.add_paragraph('tacacs-server host  {{servidor_TACACS.IP_Servidor}}  key  {{servidor_TACACS.CLAVE_Servidor}} ')
document.add_paragraph('{% endfor %}')
document.add_paragraph('aaa group server tacacs+ TACACS+CG')
document.add_paragraph('{% for servidor_TACACS in servidores_TACACS %}')
document.add_paragraph('server  {{servidor_TACACS.IP_Servidor}} ')
document.add_paragraph('{% endfor %}')
document.add_paragraph('exit')
document.add_paragraph('{{servidor_TACACS.IP_Servidor}} Es la dirección IP de cada uno de los servidores TACACS+.')
document.add_paragraph('{{servidor_TACACS.CLAVE_Servidor}} Es la clave de autenticación entre el EDC y el TACACS+.')
document.add_paragraph('En futuras versiones de IOS este último modelo será eliminado, por lo que es conveniente que se comience a utilizar el nuevo en el mayor número de plataformas posibles.')
document.add_paragraph('Configuración de los parámetros de autenticación por TACACS+.')
document.add_paragraph('aaa authentication login default group TACACS+CG local')
document.add_paragraph('aaa authentication enable default group TACACS+CG enable')
document.add_paragraph('Configuración del accounting de comandos por TACACS+.')
document.add_paragraph('aaa accounting exec default start-stop group TACACS+CG')
document.add_paragraph('aaa accounting commands 0 default start-stop group TACACS+CG')
document.add_paragraph('aaa accounting commands 1 default start-stop group TACACS+CG')
document.add_paragraph('aaa accounting commands 15 default start-stop group TACACS+CG')
document.add_paragraph('¡¡¡ En este momento es necesario finalizar la sesión y entrar de nuevo en el equipo con los nuevos credenciales para continuar con la configuración, de otra forma se perderá la conectividad !!!')
document.add_paragraph('Configuración de la autorización de comandos por TACACS+. ')
document.add_paragraph('aaa authorization exec default group TACACS+CG if-authenticated')
document.add_paragraph('aaa authorization commands 0 default group TACACS+CG local')
document.add_paragraph('aaa authorization commands 1 default group TACACS+CG local')
document.add_paragraph('aaa authorization commands 15 default group TACACS+CG local')

document.add_heading('2.1.8. Configuración de NTP', 3)
document.add_paragraph('Se configuran los servidores NTP que el EDC utilizará para sincronizar temporalmente. También se define una ACL para limitar las IPs desde las que se admiten paquetes NTP.')
document.add_paragraph('{% for servidor_NTP in servidores_NTP %}')
document.add_paragraph('{% if loop.first  %}')
document.add_paragraph('ntp server  {{servidor_NTP.IPServidor}}  prefer')
document.add_paragraph('{% else %}')
document.add_paragraph('ntp server  {{servidor_NTP.IPServidor}}')
document.add_paragraph('{% endif %}')
document.add_paragraph('{% endfor %}')
document.add_paragraph('access-list 53 remark Gestion NTP')
document.add_paragraph('{% for servidor_NTP in servidores_NTP %}')
document.add_paragraph('access-list 53 permit host  {{servidor_NTP.IPServidor}} ')
document.add_paragraph('{% endfor %}')
document.add_paragraph('access-list 53 deny any')
document.add_paragraph('ntp access-group peer 53')
document.add_paragraph('{{servidor_NTP.IPServidor}} Es la dirección IP de cada uno de los servidores NTP.-#}')

document.add_heading('2.1.9. Configuración SNMP', 3)
document.add_paragraph('Se crea un filtro para controlar los accesos de lectura SNMP.')
document.add_paragraph('access-list 50 remark Gestion SNMP lectura')
document.add_paragraph('{% for servidor_SNMP in servidores_SNMP %}')
document.add_paragraph('access-list 50 permit host  {{servidor_SNMP.CentroGestion}} {{servidor_SNMP.MascaraInversa}} ')
document.add_paragraph('{% endfor %}')
document.add_paragraph('access-list 50 deny any')
document.add_paragraph('{{servidor_SNMP.CentroGestion}} Es un rango de direcciones IP desde el que se permiten accesos de lectura SNMP.')
document.add_paragraph('{{servidor_SNMP.MascaraInversa}} ')
document.add_paragraph('Se crea otro filtro para controlar los accesos de lectura/escritura SNMP.')
document.add_paragraph('access-list 51 remark Gestion SNMP escritura ')
document.add_paragraph('{% for servidor_SNMP in servidores_SNMP %}')
document.add_paragraph('access-list 51 permit {{servidor_SNMP.CentroGestion}} {{servidor_SNMP.MascaraInversa}} ')
document.add_paragraph('{% endfor %}')
document.add_paragraph('access-list 51 deny any')
document.add_paragraph('{{servidor_SNMP.CentroGestion}} Es un rango de direcciones IP desde el que se permiten accesos de lectura/escritura SNMP.')
document.add_paragraph('{{servidor_SNMP.MascaraInversa}} ')
document.add_paragraph('Datos administrativos:')
document.add_paragraph('snmp-server location  {{Localizacion_EDC}} ')
document.add_paragraph('snmp-server chassis-id  {{Mnemonico_EDC}} ')
document.add_paragraph('snmp-server contact  {{Persona_de_Contacto}} ')
document.add_paragraph('{{Localizacion_EDC}} ')
document.add_paragraph('{{Mnemonico_EDC}} ')
document.add_paragraph('{{Persona_de_Contacto}} ')
document.add_paragraph('Comunidades de lectura y lectura/escritura.')
document.add_paragraph('snmp-server community  {{Comunidad_SNMP_Lectura}}  RO 50')
document.add_paragraph('snmp-server community  {{Comunidad_SNMP_Escritura}}  RW 51')
document.add_paragraph('{{Comunidad_SNMP_Lectura}} ')
document.add_paragraph('{{Comunidad_SNMP_Escritura}} ')
document.add_paragraph('Control de accesos TFTP.')
document.add_paragraph('{% if modelo_equipo == "Cisco C9200L" or modelo_equipo == "Cisco C9300L" %}')
document.add_paragraph('snmp-server file-transfer access-group 51 protocol tftp')
document.add_paragraph('{% endif %}')
document.add_paragraph('snmp-server tftp-server-list 51')
document.add_paragraph('Se añade persistencia a los índices de los interfaces del equipo.')
document.add_paragraph('snmp-server ifindex persist')

document.add_heading('2.1.10. Activación de traps SNMP', 3)
document.add_paragraph('Cada servicio requerirá la activación de unas traps SNMP determinadas.')

document.add_heading('2.1.10.1. MacroLAN', 4)
document.add_paragraph('{% if servicio == "MacroLAN" %}')
document.add_paragraph('    snmp-server enable traps')
document.add_paragraph('    no snmp-server enable traps snmp authentication')
document.add_paragraph('    no snmp-server enable traps syslog')
document.add_paragraph('    {% if Ejecutar_Comando %}')
document.add_paragraph('    no snmp-server enable traps isdn')
document.add_paragraph('    snmp-server enable traps isdn call-information')
document.add_paragraph('    {% endif %}')
document.add_paragraph('{% endif %}')

document.add_heading('2.1.10.2. VPNIP', 4)
document.add_paragraph('{% if servicio == "VPNIP" %}')
document.add_paragraph('    {% if modelo_equipo != "Cisco C1000" and modelo_equipo != "Cisco C9200L" and modelo_equipo != "Cisco C9300L" %}')
document.add_paragraph('    snmp-server enable traps isdn call-information ')
document.add_paragraph('    {% endif %}')
document.add_paragraph('    snmp-server enable traps config')
document.add_paragraph('    snmp-server enable traps entity')
document.add_paragraph('    {% if modelo_equipo != "Cisco ASR1001-X" and modelo_equipo != "Cisco ASR1009-X" and modelo_equipo != "Cisco ASR920" and modelo_equipo != "Cisco ASR903" and modelo_equipo != "Familia ISR4000" and modelo_equipo != "Familia ISR1100" %}')
document.add_paragraph('    snmp-server enable traps envmon')
document.add_paragraph('    {% endif %}')
document.add_paragraph('    {% if modelo_equipo != "Cisco C1000" and modelo_equipo != "Cisco C9200L" and modelo_equipo != "Cisco C9300L" %}')
document.add_paragraph('    snmp-server enable traps bgp ')
document.add_paragraph('    snmp-server enable traps frame-relay ')
document.add_paragraph('    snmp-server enable traps rtr ')
document.add_paragraph('    {% endif %}')
document.add_paragraph('    {% if Ejecutar_Comando %}')
document.add_paragraph('    snmp-server enable traps isdn ')
document.add_paragraph('    {% endif %}')
document.add_paragraph('    snmp-server enable traps snmp linkup linkdown coldstart warmstart')
document.add_paragraph('    {% if modelo_equipo != "Cisco C1000" and modelo_equipo != "Cisco C9200L" and modelo_equipo != "Cisco C9300L" %}')
document.add_paragraph('    snmp-server enable traps atm pvc')
document.add_paragraph('    {% endif %}')
document.add_paragraph('{% endif %}')

document.add_heading('2.1.10.3. DataInternet', 4)
document.add_paragraph('{% if servicio == "DataInternet" %}')
document.add_paragraph('    snmp-server enable traps config')
document.add_paragraph('    {% if modelo_equipo != "Cisco ASR1001-X" and modelo_equipo != "Cisco ASR1009-X" and modelo_equipo != "Cisco ASR920" and modelo_equipo != "Cisco ASR903" and modelo_equipo != "Familia ISR4000" and modelo_equipo != "Familia ISR1100" %} ')
document.add_paragraph('    snmp-server enable traps envmon')
document.add_paragraph('    {% endif %}')
document.add_paragraph('    {% if modelo_equipo != "Cisco C1000" and modelo_equipo != "Cisco C9200L" and modelo_equipo != "Cisco C9300L" %}')
document.add_paragraph('    snmp-server enable traps bgp ')
document.add_paragraph('    snmp-server enable traps rtr ')
document.add_paragraph('    {% endif %}')
document.add_paragraph('    snmp-server enable traps snmp linkup linkdown coldstart warmstart')
document.add_paragraph('    {% if modelo_equipo != "Cisco C1000" and modelo_equipo != "Cisco C9200L" and modelo_equipo != "Cisco C9300L" %}')
document.add_paragraph('    snmp-server enable traps atm pvc ')
document.add_paragraph('    {% endif %}')
document.add_paragraph('{% endif %}')

document.add_heading('2.1.10.4. SiLAN e Ibercom IP Punto Central', 4)
document.add_paragraph('{% if servicio == "SILAN" or servicio == "Ibercom Punto Central" %}')
document.add_paragraph('    snmp-server enable traps')
document.add_paragraph('{% endif %}')

document.add_heading('2.1.10.5. Destino de los traps', 4)
document.add_paragraph('Atención: La IP de la colectora no debe configurarse de forma manual, los sistemas realizarán una configuración automática con la IP asignada. La configuración manual de esta IP puede provocar un mal funcionamiento de los sistemas colectores de alarmas, por lo que debe evitarse.')
document.add_paragraph('En caso de que sea necesaria la configuración manual por alguna necesidad que lo justifique se utilizará la configuración que se detalla a continuanción.')

document.add_heading('2.1.11. Configuración de RMON', 3)

document.add_heading('2.1.11.1. Servicios MacroLAN, VPNIP y DataInternet', 4)
document.add_paragraph('{% if servicio == "MacroLAN" or  servicio == "VPNIP" or servicio == "DataInternet" %}')
document.add_paragraph('Definición de EVENTOS y ALARMAS RMON para variables MIB de una única instancia')
document.add_paragraph('    rmon event 100 log trap  {{Comunidad_Lectura_1}}  description NUM_INTERFACES_HA_CAMBIADo owner config')
document.add_paragraph('    rmon event 200 log trap  {{Comunidad_Lectura_1}}  description MEMoRIA_LIBRE_SUPERIoR_A_500K owner config')
document.add_paragraph('    rmon event 201 log trap  {{Comunidad_Lectura_1}}  description MEMoRIA_LIBRE_INFERIoR_A_500K owner config')
document.add_paragraph('    rmon event 300 log trap  {{Comunidad_Lectura_1}}  description SUPERADo_UMBRAL_DE_USo_DE_CPU owner config')
document.add_paragraph('    rmon event 301 log trap  {{Comunidad_Lectura_1}}  description USo_DE_CPU_ACEPTABLE owner config')
document.add_paragraph('    rmon alarm 100 interfaces.1.0 900 delta rising-threshold 1 100 falling-threshold -1 100 owner config')
document.add_paragraph('    rmon alarm 200 lsystem.8.0 3600 absolute rising-threshold 500000 200 falling-threshold 500000 201 owner config')
document.add_paragraph('    rmon alarm 300 lsystem.58.0 900 absolute rising-threshold 70 300 falling-threshold 55 301 owner config')
document.add_paragraph('{{Comunidad_Lectura_1}}')
document.add_paragraph('En esta plantilla se definen las siguientes ALARMAS y EVENTOS RMON:')
document.add_paragraph('•	Alarma 100: ')
document.add_paragraph('o	Se encarga de la monitorización de la variable MIB ifNumber (.1.3.6.1.2.1.2.1.0) cuyo valor indica el número de interfaces de red presentes en el equipo, independientemente del estado en el que se encuentran.')
document.add_paragraph('o	Esta variable MIB se monitoriza cada 900 segundos (15 minutos).')
document.add_paragraph('o	Esta asociada a un único EVENTO > 100. De manera que se generará el Trap SNMP asociado a la superación de la alarma RMON 100 cada vez que el número de interfaces cambie al aumentar en 1 o al decrecer en 1.')
document.add_paragraph('•	Alarma 200:')
document.add_paragraph('o	Se encarga de la monitorización de la variable MIB freeMem (.1.3.6.1.4.1.9.2.1.8.0) cuyo valor indica la cantidad de memoria libre en bytes.')
document.add_paragraph('o	Esta variable MIB se monitoriza cada 3600 segundos (1 hora)).')
document.add_paragraph('o	Evento de SUBIDA = 200 > Se generará un Trap SNMP de RMON por superación del Umbral de Subida asociado a la Alarma 200 cuando el valor de la variable MIB freeMem sea superior a 500000 bytes.')
document.add_paragraph('o	Evento de BAJADA = 201 > Se generará un Trap SNMP de RMON por superación del Umbral de Bajada asociada a la Alarma 200 cuando el valor de la variable MIB freeMem sea inferior a 500000 bytes.')
document.add_paragraph('•	Alarma 300:')
document.add_paragraph('o	Se encarga de la monitorización de la variable MIB avgBusy5 (.1.3.6.1.4.1.9.2.1.58.0) cuyo valor indica el porcentaje de consumo de CPU en los últimos 5 minutos.')
document.add_paragraph('o	Evento de SUBIDA = 300 > Se generará un Trap SNMP de RMON por superación del Umbral de Subida asociado a la Alarma 300 cuando el valor de la variable MIB avgBusy5 sea superior al 70%.')
document.add_paragraph('o	Evento de BAJADA = 301 > Se generará un Trap SNMP de RMON por superación del Umbral de Bajada asociada a la Alarma 300 cuando el valor de la variable MIB avgBusy5 sea inferior al 55%.')
document.add_paragraph('Definición de EVENTOS y ALARMAS RMON para variables MIB de varias instancias ')
document.add_paragraph('    rmon event 52 log trap  {{Comunidad_Lectura_2}}  description DESCARTES_DE_ENTRADA_MAL owner config ')
document.add_paragraph('    rmon event 53 log trap  {{Comunidad_Lectura_2}}  description DESCARTES_DE_ENTRADA_BIEN owner config ')
document.add_paragraph('    rmon event 54 log trap  {{Comunidad_Lectura_2}}  description ERRORES_DE_ENTRADA_MAL owner config ')
document.add_paragraph('    rmon event 55 log trap  {{Comunidad_Lectura_2}}  description ERRORES_DE_ENTRADA_BIEN owner config ')
document.add_paragraph('    rmon event 56 log trap  {{Comunidad_Lectura_2}}  description DESCARTES_DE_SALIDA_MAL owner config ')
document.add_paragraph('    rmon event 57 log trap  {{Comunidad_Lectura_2}}  description DESCARTES_DE_SALIDA_BIEN owner config ')
document.add_paragraph('    rmon event 58 log trap  {{Comunidad_Lectura_2}}  description ERRORES_DE_SALIDA_MAL owner config ')
document.add_paragraph('    rmon event 59 log trap  {{Comunidad_Lectura_2}}  description ERRORES_DE_SALIDA_BIEN owner config ')
document.add_paragraph('    rmon event 62 log trap  {{Comunidad_Lectura_2}}  description ERRORES_COLISIONES owner config')
document.add_paragraph('    rmon event 63 log trap  {{Comunidad_Lectura_2}}  description ERRORES_COLISIONES_RECUPERADAS owner config')
document.add_paragraph('    {% for alarma in monitorizacion_variables_MIB %}')
document.add_paragraph('    rmon alarm {{alarma.codigo_alarma}} {{alarma.OID}} {{alarma.instancia}} {{alarma.Y}}  delta rising-threshold  {{alarma.Z}}  {{alarma.Evento_SUBIDA}} falling-threshold  {{alarma.Z1}}  {{alarma.Evento_BAJADA}} owner config ')
document.add_paragraph('    {% endfor %}')
document.add_paragraph('{% endif %}')
document.add_paragraph('{{Comunidad_Lectura_2}}')
document.add_paragraph('{{alarma.codigo_alarma}}')
document.add_paragraph('{{alarma.OID}}')
document.add_paragraph('{{alarma.instancia}} valor númerico entero que define la instancia de la variable MIB asociada al interfaz que cuya variable MIB asociada deseamos monitorizar.')
document.add_paragraph('{{alarma.Y}} tiempo definido en segundos que indica el periodo de tiempo cada cuanto deseamos monitorizar el valor de la variable MIB definida en la alarma.')
document.add_paragraph('{{alarma.Z}} Valor del umbral de SUBIDA. Este valor deberá estar expresado en las mismas unidades que utilice la variable MIB que está siendo monitorizada.')
document.add_paragraph('{{alarma.Evento_SUBIDA}} ')
document.add_paragraph('{{alarma.Z1}} Valor del umbral de BAJADA. Este valor deberá estar expresado en las mismas unidades que utilice la variable MIB que está siendo monitorizada.')
document.add_paragraph('{{alarma.Evento_BAJADA}}')
document.add_paragraph('Donde: ')
document.add_paragraph('•	Se configurará un CÓDIGO de Alarma distinto para cada instancia que deseemos monitorizar de una determinada Variable MIB.')
document.add_paragraph('•	El código de la Alarma será un número de 5 dígitos, donde los dos primeros dígitos corresponden con el primer código de EVENTO PAR (Evento asociado a la superación del Umbral de Subida). Los tres últimos dígitos se numerará consecutivamente, uno para cada instancia, desde el valor "000" hasta el valor "999" (1000 posibles valores)')
document.add_paragraph('Por ejemplo: se podrán configurar 999 alarmas con los códigos 62000 hasta 62999 para poder monitorizar hasta 999 instancias de la variable MIB locIfInCollisions.')
document.add_paragraph('•	<instancia> > valor númerico entero que define la instancia de la variable MIB asociada al interfaz que cuya variable MIB asociada deseamos monitorizar.')
document.add_paragraph('•	<Y> > tiempo definido en segundos que indica el periodo de tiempo cada cuanto deseamos monitorizar el valor de la variable MIB definida en la alarma.')
document.add_paragraph('•	<Z> > Valor del umbral de SUBIDA. Este valor deberá estar expresado en las mismas unidades que utilice la variable MIB que está siendo monitorizada.')
document.add_paragraph('•	<Z1> > Valor del umbral de BAJADA. Este valor deberá estar expresado en las mismas unidades que utilice la variable MIB que está siendo monitorizada.')
document.add_paragraph('En esta plantilla se definen las siguientes ALARMAS y EVENTOS RMON:')
document.add_paragraph('•	Alarma 52XXX:')
document.add_paragraph('o	Se encarga de la monitorización de la variable MIB ifInDiscards (.1.3.6.1.2.1.2.2.1.13.<instancia>) cuyo valor indica el número de paquetes entrantes que han sido elegidos para ser descartados incluso aunque no se hayan detectado errores en ellos.')
document.add_paragraph('o	Esta variable MIB se monitoriza cada <Y> segundos.')
document.add_paragraph('o	Evento de SUBIDA = 52 > Se generará un Trap SNMP de RMON por superación del Umbral de Subida asociado a la Alarma 52XXX cuando el valor de la variable MIB ifInDiscards.<instancia> sea superior a <Z>.')
document.add_paragraph('o	Evento de BAJADA = 53 > Se generará un Trap SNMP de RMON por superación del Umbral de Bajada asociada a la Alarma 52XXX cuando el valor de la variable MIB ifInDiscards.<instancia> sea inferior a <Z1>.')
document.add_paragraph('•	Alarma 54XXX:')
document.add_paragraph('o	Se encarga de la monitorización de la variable MIB ifInErrors (.1.3.6.1.2.1.2.2.1.14.<instancia>) cuyo valor indica el número de paquetes entrantes que contenían errores de manera que no han podido ser entregados a protocolos de capas superiores para su procesado.')
document.add_paragraph('o	Esta variable MIB se monitoriza cada <Y> segundos.')
document.add_paragraph('o	Evento de SUBIDA = 54 > Se generará un Trap SNMP de RMON por superación del Umbral de Subida asociado a la Alarma 54XXX cuando el valor de la variable MIB ifInDiscards.<instancia> sea superior a <Z>.')
document.add_paragraph('o	Evento de BAJADA = 55 > Se generará un Trap SNMP de RMON por superación del Umbral de Bajada asociada a la Alarma 54XXX cuando el valor de la variable MIB ifInDiscards.<instancia> sea inferior a <Z1>.')
document.add_paragraph('•	Alarma 56XXX:')
document.add_paragraph('o	Se encarga de la monitorización de la variable MIB ifOutDiscards (.1.3.6.1.2.1.2.2.1.19.<instancia>) cuyo valor indica el número de paquetes salientes que han sido elegidos para ser descartados incluso aunque no se hayan detectado errores en ellos para evitar que sean trasmitidos.')
document.add_paragraph('o	Esta variable MIB se monitoriza cada <Y> segundos.')
document.add_paragraph('o	Evento de SUBIDA = 56 > Se generará un Trap SNMP de RMON por superación del Umbral de Subida asociado a la Alarma 56XXX cuando el valor de la variable MIB ifOutDiscards.<instancia> sea superior a <Z>.')
document.add_paragraph('o	Evento de BAJADA = 57 > Se generará un Trap SNMP de RMON por superación del Umbral de Bajada asociada a la Alarma 56XXX cuando el valor de la variable MIB ifOutDiscards.<instancia> sea inferior a <Z1>.')
document.add_paragraph('•	Alarma 58XXX: ')
document.add_paragraph('o	Se encarga de la monitorización de la variable MIB ifOutErrors (.1.3.6.1.2.1.2.2.1.20.<instancia>) cuyo valor indica el número de paquetes salientes que contenían errores de manera que no han podido ser transmitidos.')
document.add_paragraph('o	Esta variable MIB se monitoriza cada <Y> segundos.')
document.add_paragraph('o	Evento de SUBIDA = 58 > Se generará un Trap SNMP de RMON por superación del Umbral de Subida asociado a la Alarma 58XXX cuando el valor de la variable MIB ifInDiscards.<instancia> sea superior a <Z>.')
document.add_paragraph('o	Evento de BAJADA = 59 > Se generará un Trap SNMP de RMON por superación del Umbral de Bajada asociada a la Alarma 58XXX cuando el valor de la variable MIB ifInDiscards.<instancia> sea inferior a <Z1>.')
document.add_paragraph('•	Alarma 62XXX:')
document.add_paragraph('o	Se encarga de la monitorización de la variable MIB locIfCollisions (.1.3.6.1.4.1.9.2.2.1.1.25.<instancia>) cuyo valor indica el número de colisiones en salida detectadas en el interfaz al que hace referencia la <instancia>.')
document.add_paragraph('o	Esta variable MIB se monitoriza cada <Y> segundos.')
document.add_paragraph('o	Evento de SUBIDA = 62 > Se generará un Trap SNMP de RMON por superación del Umbral de Subida asociado a la Alarma 62XXX cuando el valor de la variable MIB locIfCollisions.<instancia> sea superior a <Z>.')
document.add_paragraph('o	Evento de BAJADA = 63 > Se generará un Trap SNMP de RMON por superación del Umbral de Bajada asociada a la Alarma 62XXX cuando el valor de la variable MIB locIfCollisions.<instancia> sea inferior a <Z1>.')

document.add_heading('2.1.11.2. SILAN', 4)
document.add_paragraph('{% if servicio == "SILAN" %}')
document.add_paragraph('    rmon event 46 log trap  {{Comunidad_Lectura_3}}  description ERRORES_CoLISIoNES owner config')
document.add_paragraph('    rmon event 47 log trap  {{Comunidad_Lectura_3}}  description ERRORES_CoLISIoNES_RECUPERADAS owner config')
document.add_paragraph('    rmon event 100 log trap  {{Comunidad_Lectura_3}}  description NUM_INTERFACES_HA_CAMBIADO owner config')
document.add_paragraph('    rmon event 200 log trap  {{Comunidad_Lectura_3}}  description MEMORIA_LIBRE_SUPERIOR_A_500K owner config')
document.add_paragraph('    rmon event 201 log trap  {{Comunidad_Lectura_3}}  description MEMORIA_LIBRE_INFERIOR_A_500K owner config')
document.add_paragraph('    rmon event 300 log trap  {{Comunidad_Lectura_3}}  description SUPERADO_UMBRAL_DE_USO_DE_CPU owner config')
document.add_paragraph('    rmon event 301 log trap  {{Comunidad_Lectura_3}}  description USO_DE_CPU_ACEPTABLE owner config')
document.add_paragraph('    rmon alarm 100 ifNumber.0 900 delta rising-threshold 1 100 falling-threshold -1 100 owner config')
document.add_paragraph('    rmon alarm 200 lsystem.8.0 3600 absolute rising-threshold 500000 200 falling-threshold 500000 201 owner config')
document.add_paragraph('    rmon alarm 300 lsystem.58.0 900 absolute rising-threshold 70 300 falling-threshold 55 301 owner config')
document.add_paragraph('    rmon alarm 46001 lifEntry.25.10001 900 delta rising-threshold 100 46 falling-threshold 100 47 owner config')
document.add_paragraph('{% endif %}')
document.add_paragraph('{{Comunidad_Lectura_3}}')

document.add_heading('2.1.11.3. Ibercom Punto Central', 4)
document.add_paragraph('{% if servicio == "Ibercom Punto Central" %}')
document.add_paragraph('    rmon event 46 log trap  {{Comunidad_Lectura_4}}  description ERRORES_COLISIoNES owner config')
document.add_paragraph('    rmon event 47 log trap  {{Comunidad_Lectura_4}}  description ERRORES_COLISIoNES_RECUPERADAS owner config')
document.add_paragraph('    rmon event 100 log trap  {{Comunidad_Lectura_4}}  description NUM_INTERFACES_HA_CAMBIADO owner config')
document.add_paragraph('    rmon event 200 log trap  {{Comunidad_Lectura_4}}  description MEMORIA_LIBRE_SUPERIOR_A_500K owner config')
document.add_paragraph('    rmon event 201 log trap  {{Comunidad_Lectura_4}}  description MEMORIA_LIBRE_INFERIOR_A_500K owner config')
document.add_paragraph('    rmon event 300 log trap  {{Comunidad_Lectura_4}}  description SUPERADO_UMBRAL_DE_USO_DE_CPU owner config')
document.add_paragraph('    rmon event 301 log trap  {{Comunidad_Lectura_4}}  description USO_DE_CPU_ACEPTABLE owner config')
document.add_paragraph('    rmon alarm 100 interfaces.1.0 900 delta rising-threshold 1 100 falling-threshold -1 100 owner config')
document.add_paragraph('    rmon alarm 200 lsystem.8.0 3600 absolute rising-threshold 500000 200 falling-threshold 500000 201 owner config')
document.add_paragraph('    rmon alarm 300 lsystem.58.0 900 absolute rising-threshold 70 300 falling-threshold 55 301 owner config')
document.add_paragraph('    rmon alarm 46001 1.3.6.1.4.1.9.2.2.1.1.25. {{X}}  900 delta rising-threshold 100 46 falling-threshold 100 47 owner config')
document.add_paragraph('{% endif %}')
document.add_paragraph('{{Comunidad_Lectura_4}}')
document.add_paragraph('{{X}} Corresponde a la instancia SNMP del interfaz LAN cuyas colisiones deseamos monitorizar.')
document.add_paragraph('NOTA: Para este servicio sólo tiene sentido en la interfaz LAN de cliente. El valor de <X>, del tipo de alarma 46001, dependerá de cada equipo, ya que hace referencia al número que le asigna el router al arrancar, por lo que es obligación del centro que quiera implementar esta parte del RMON buscar cuál es el que hace referencia a la interfaz que queremos chequear. Para saber cuál es, se puede realizar la siguiente acción.')

document.add_heading('2.1.12. Configuración de Syslog', 3)
document.add_paragraph('logging buffered  {{Tamano_Buffer}}  debugging')
document.add_paragraph('no logging console')
document.add_paragraph('logging facility  {{Local_x}} ')
document.add_paragraph('logging  {{IPServidorSyslog}} ')
document.add_paragraph('logging trap informational')
document.add_paragraph('logging rate-limit console 10 except errors')
document.add_paragraph('{{Tamano_Buffer}} Es el tamaño máximo, en bytes, del buffer utilizado para almacenar los mensajes de "log". Se recomienda un valor de 100000, equivalente aproximadamente a 100KB.')
document.add_paragraph('{{Local_x}} Se particularizará al valor que se defina en el servidor Syslog del Centro de Gestión.')
document.add_paragraph('{{IPServidorSyslog}} Es la dirección IP del servidor Syslog en el Centro de Gestión.')
document.add_paragraph('Donde: ')
document.add_paragraph('<Tamaño_Buffer> Es el tamaño máximo, en bytes, del buffer utilizado para almacenar los mensajes de "log". Se recomienda un valor de 100000, equivalente aproximadamente a 100KB. ')
document.add_paragraph('<Local_x> Se particularizará al valor que se defina en el servidor Syslog del Centro de Gestión. ')
document.add_paragraph('<IPServidorSyslog> Es la dirección IP del servidor Syslog en el Centro de Gestión. ')
document.add_paragraph('')
document.add_paragraph('Donde: ')
document.add_paragraph('')
document.add_paragraph('Donde: ')
document.add_paragraph('')
document.add_paragraph('Donde: ')
document.add_paragraph('')
document.add_paragraph('Donde:')
document.add_paragraph('<X> Corresponde a la instancia SNMP del interfaz LAN cuyas colisiones deseamos monitorizar.')
document.add_paragraph('NOTA: Para este servicio sólo tiene sentido en la interfaz LAN de cliente. El valor de <X>, del tipo de alarma 46001, dependerá de cada equipo, ya que hace referencia al número que le asigna el router al arrancar, por lo que es obligación del centro que quiera implementar esta parte del RMON buscar cuál es el que hace referencia a la interfaz que queremos chequear. Para saber cuál es, se puede realizar la siguiente acción.')

document.save('word_automatico_render.docx')
