---
- hosts: all
  connection: network_cli
  gather_facts: 'no'
  vars : 
    cars: ['Mercedes' , ' Ford' , 'Nissan' ]

  tasks: 
    - name: A Loop example 
      template: 
        src: ./template.j2 
        dest: ./jinja2/output.txt

    - name: This command will change the working directory to somedir/
      shell:
        cmd: ls -la

    - name: This command will change the working directory to somedir/
      shell:
        cmd: cd jinja2 | ls -la

    - name: This command 
      shell:
        cmd: pwd

    - name: This command 
      shell:
        cmd: cat ./jinja2/output.txt



