---
- hosts: all
  connection: network_cli
  gather_facts: 'no'
  vars : 
    cars: ['Mercedes','Ford','Nissan']

  tasks: 
    - name: A Loop example 
      template: 
        src: ./template.j2 
        dest: ./jinja2/output.txt

    - name: This command will change the working directory to somedir/
      shell:
        cmd: ls -la

    - name: This command will change the working directory to somedir/
      shell:
        cmd: git config --list

    - name: This command 
      shell:
        cmd: git branch

    - name: OUTPUT 
      shell:
        cmd: cat ./jinja2/output.txt

