---
- hosts: all
  connection: network_cli
  gather_facts: 'no'
  vars_files:
    - rutas.yml


  tasks: 
    - name: A Loop example 
      template: 
        src: ./template_if.j2 
        dest: ./jinja3/output.txt
        lstrip_blocks: yes

    - name: OUTPUT 
      shell:
        cmd: cat ./jinja3/output.txt